### ISSUE TITLE
Centering buttons help

### ISSUE THREAD

**Issue by dvirlar2** [samanthacsik/samanthacsik.github.io#12]
Yes I was stalking your website late at night for inspiration, I won't apologize! 🤪 

Anyways... I saw in your [index.qmd](https://github.com/samanthacsik/samanthacsik.github.io/blob/main/talks_workshops/2022-10-10-customizing-quarto-websites/index.qmd) for your customizing quarto workshop page that you tried to center some buttons but that it didn't work (since they aren't centered on your site).

I would like to oh-so-humbly recommend the use of the following code:
```
<center>
   [your button code]
   [your second button code]
</center>
```

I used that on a page I'm still developing and it worked out 👀  okay bye!

**Comment by samanthacsik** [comment]
Finally ended up figuring this out (sort of, I think?). 

Here's the CSS:

```{css}
.container { 
  height: 20px;
  position: relative;
}

.center { 
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}
```

And the HTML:

```{html}
<div class="container">
<div class="center">
<button type="button" class="button-styling" onclick=window.location.href='https://ucsb-meds.github.io/EDS430-Shiny/#/title-slide/'>{{< fa tv title="A television screen" >}} slides</button>
<button type="button" class="button-styling" onclick=window.location.href='https://github.com/UCSB-MEDS/EDS430-Shiny'>{{< fa code title="A symbol for code, </>" >}} source code</button>
</div>
</div>
```
